import { IsNotEmpty, IsNumber, IsString } from "class-validator";

export class CreateListingDto {
    
    id?: string; //generated by mongo

    @IsNotEmpty()
    @IsString()
    name: string;

    @IsNotEmpty()
    @IsString()
    description: string;  

    @IsNotEmpty()
    @IsNumber()
    price: number;

    @IsNotEmpty()
    @IsString()
    userId: string;

    views: number = 0;
}
